autoupdate_schedule: quarterly
default_language_version:
    python: python3
exclude: '^notebooks/'
repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.0.239'
  hooks:
    - id: ruff

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.4.0'
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml

- repo: https://github.com/psf/black
  rev: '22.12.0' #make sure to sync with blackdoc beneath
  hooks:
    - id: black
