name: scale-aware-air-sea
channels:
  - conda-forge
  - numba
dependencies:
  - python=3.9
  - xarray
  - esmpy
  - xesmf
  - zarr
  - fsspec
  - ipykernel
  - intake
  - numba
  - numpy
  - gcsfs
  - intake-xarray
  - matplotlib
