name: test_env_scale_aware_air_sea
channels:
  - conda-forge
dependencies:
  - aerobulk-python
  - codecov
  - gcm_filters
  - numpy
  - pip
  - pytest
  - pytest-cov
  - python
  - tqdm
  - xarray
  - zarr
